In [1]:
import json
import re
import pandas as pd
from nltk import word_tokenize
from nltk.corpus import stopwords
import string

input_file_indeed = '.\\indeed_listings.json'
input_file_techno_jobs = '.\\technojobs_listings.json'
input_file_reed = '.\\Reed_listings.json'
input_file_24 = '.\\jobs24_listings.json'
input_file_jobs_today = '.\\jobs_today_listings.json'



output_file = '.\\all_jobs.json'

In [2]:
##LOADING AND CONCATING THE DATA
with open(input_file_indeed) as f:
    data_indeed = json.load(f)

with open(input_file_techno_jobs) as f:
    data_techno = json.load(f)
    
with open(input_file_reed) as f:
    data_reed = json.load(f)

with open(input_file_24) as f:
    data_24 = json.load(f)
    
with open(input_file_jobs_today) as f:
    data_today = json.load(f)

In [3]:
def lowercase_strip_reed_techno(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(' ','').split(',')[-1]
        return sentence
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''
    
def lowercase_strip_indeed(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(' ','').split('-')[-1]
        return sentence
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''

def lowercase_strip_24(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(' ','').split(',')[0]
        return sentence
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''
    
def lowercase_strip_today1(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('Posted', '').replace('Salary', '').replace('\r', '').replace('\t', '').replace('\n', '').replace('Recruiter','').strip().split(',')
        return sentence[0]
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''
    
def lowercase_strip_today2(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
#         sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(' ','').split(',')[0]
        return sentence[4]
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''
    
def lowercase_strip_indeed2(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        wanted_list = ['day', 'month', 'year','months', 'days']
        sentence = [word for word in sentence if 'day' in word or 'month' in word ]
        if len(sentence) > 0:
            result = sentence[0].replace('-','').strip()
        else:
            result = 'Not available'
        return result
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''
    
def lowercase_strip_technojob(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\t', '').replace('\n', '').replace('Recruiter','').strip().split(',')
        return sentence[0]
    elif isinstance(sentence, (str,)):
        result = sentence.replace('\n','').strip().lower()
        return result
    else:
        return ''
    
    
def lowercase_strip_reed(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(',','.').replace('..','.').strip()
        return sentence
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''    
    
  
    
def lowercase_strip_reed2(sentence):
    '''
    strip all the non-alphabetical characters
    '''
    if isinstance(sentence, (list,)):
        sentence = ' '.join(sentence).replace('\r', '').replace('\n', '').replace(',','.').replace('..','.').strip().split(' ')[1]
        return sentence
    elif isinstance(sentence, (str,)):
        clean_text = sentence.strip().lower()
        result = re.sub(r"[^a-zA-Z]+", ' ', clean_text)
        return result
    else:
        return ''

In [4]:
STOPWORD = stopwords.words('english') + list(string.punctuation)

In [5]:
def clean_discription(descrip_list):
    if isinstance(descrip_list, (list,)):
        descrip_list = ' '.join(descrip_list).replace('\r', '').replace('\n', '').replace('\t','').strip()
#         clean_descrip =' '.join([i for i in word_tokenize(descrip_list.lower()) if i not in STOPWORD])
    return descrip_list

In [6]:
for i in data_today:
    location_clean = lowercase_strip_today2(i['location'])
    d1 = {'location': location_clean}
    company_clean = lowercase_strip_today1(i['company'])
    d2 = {'company': company_clean}
    title_clean = lowercase_strip_today2(i['title'])
    d3 = {'title': title_clean}
    descrip_clean = clean_discription(i['description'])
    d4 = {'description': descrip_clean}
    salary_clean = lowercase_strip_today1(i['salary'])
    d5 = {'salary': salary_clean}
    posted_clean = lowercase_strip_today1(i['date_listed'])
    d6 = {'date_listed': posted_clean}

    
    i.update(d1)
    i.update(d2)
    i.update(d3)
    i.update(d4)
    i.update(d5)
    i.update(d6)

In [7]:
for i in data_24:
    location_clean = lowercase_strip_24(i['location'])
    d1 = {'location': location_clean}
    company_clean = lowercase_strip_24(i['company'])
    d2 = {'company': company_clean}
    title_clean = lowercase_strip_24(i['title'])
    d3 = {'title': title_clean}
    descrip_clean = clean_discription(i['description'])
    d4 = {'description': descrip_clean}
    salary_clean = lowercase_strip_24(i['salary'])
    i.update(d1)
    i.update(d2)
    i.update(d3)
    i.update(d4)

In [8]:
for i in data_indeed:
    location_clean = lowercase_strip_indeed(i['location'])
    d1 = {'location': location_clean}
    company_clean = lowercase_strip_indeed(i['company'])
    d2 = {'company': company_clean}
    title_clean = lowercase_strip_indeed(i['title'])
    d3 = {'title': title_clean}
    descrip_clean = clean_discription(i['description'])
    d4 = {'description': descrip_clean}
    posted_clean = lowercase_strip_indeed2(i['date_listed'])
    d6 = {'date_listed': posted_clean}

    i.update(d1)
    i.update(d2)
    i.update(d3)
    i.update(d4)
    i.update(d6)

In [9]:

for i in data_techno:
    location_clean = lowercase_strip_reed_techno(i['location'])
    d1 = {'location': location_clean}
    company_clean = lowercase_strip_reed_techno(i['company'])
    d2 = {'company': company_clean}
    title_clean = lowercase_strip_reed_techno(i['title'])
    d3 = {'title': title_clean}
    descrip_clean = clean_discription(i['description'])
    d4 = {'description': descrip_clean}
    salary_clean = lowercase_strip_technojob(i['salary'])
    d5 = {'salary': salary_clean}
    posted_clean = lowercase_strip_technojob(i['date_listed'])
    d6 = {'date_listed': posted_clean}

    
    i.update(d1)
    i.update(d2)
    i.update(d3)
    i.update(d4)
    i.update(d5)
    i.update(d6)

In [10]:
for i in data_reed:
    location_clean = lowercase_strip_reed_techno(i['location'])
    d1 = {'location': location_clean}
    company_clean = lowercase_strip_reed_techno(i['company'])
    d2 = {'company': company_clean}
    title_clean = lowercase_strip_reed_techno(i['title'])
    d3 = {'title': title_clean}
    descrip_clean = clean_discription(i['description'])
    d4 = {'description': descrip_clean}
    salary_clean = lowercase_strip_reed(i['salary'])
    d5 = {'salary': salary_clean}
    posted_clean = lowercase_strip_reed2(i['date_listed'])
    d6 = {'date_listed': posted_clean}

    
    i.update(d1)
    i.update(d2)
    i.update(d3)
    i.update(d4)
    i.update(d5)
    i.update(d6)

In [11]:
# data_reed.extend(data_techno)
# data_reed.extend(data_indeed)
# data_reed.extend(data_24)
# data_reed.extend(data_today)

In [12]:
df_reed = pd.DataFrame(data_reed)
df_24 = pd.DataFrame(data_24)
df_today = pd.DataFrame(data_today)
df_indeed = pd.DataFrame(data_indeed)
df_techno = pd.DataFrame(data_techno)

In [13]:
df_today.tail(100)

,URL,company,date_listed,description,location,salary,title
3874,https://www.drapersjobs.com/job/2801227/partne...,Hays,15 Feb 2019,An exciting role for a Partnership Manager - B...,Birmingham,£28000.00 - £42000.00 per annum,partnership manager
3875,https://www.drapersjobs.com/job/2801226/gerber...,Freedom Recruitment,15 Feb 2019,A Leading brand known for its exsquiste Linger...,London,Negotiable,gerber pattern cutter lingerie mat cover
3876,https://www.drapersjobs.com/job/2801219/graphi...,Fashion And Retail Personnel,15 Feb 2019,This is a fantastic opportunity to join a lead...,East Midlands,£25000 - £30000 per annum + SALARY IS AN AGENC...,graphic designer childrenswear
3877,https://www.accountancyage.com/jobs/job/901506...,Robert Half,13 Feb 2019,Robert Half are exclusively partnering with a ...,"England, London",£3000 - £25000 per annum + benefits,accounts assistant
3878,https://www.drapersjobs.com/job/2801211/design...,Hays,15 Feb 2019,A Global Fashion Brand are looking for a Desig...,Manchester,£40000.00 - £60000.00 per annum,design manager
3879,https://www.drapersjobs.com/job/2801241/social...,Elite Associates,15 Feb 2019,A luxury womenswear brand renowned for their e...,London,dependent on experience,social media content editor luxury
3880,https://www.drapersjobs.com/job/2801232/ladies...,Danielle Ward Recruitment Ltd,15 Feb 2019,This successful supplier to the High Street re...,North West England,c£20-£30,ladies nightwear and loungewear designer
3881,https://www.accountancyage.com/jobs/job/901480...,Pro Finance,13 Feb 2019,Looking for a fast track route to Director? Ou...,"England, London",£60000 - £70000 per annum + Excellent Benefits,transaction advisory services senior manager
3882,https://www.drapersjobs.com/job/2801237/senior...,Hays,15 Feb 2019,An established supplier based in Manchester se...,Manchester,£35000.00 - £45000.00 per annum,senior ladieswear knitwear designer
3883,https://www.accountancyage.com/jobs/job/901493...,Robert Half,13 Feb 2019,Robert Half has partnered with an organisation...,"England, Gloucestershire",Negotiable,interim head of finance
3884,https://www.drapersjobs.com/job/2801214/denim-...,Hays,15 Feb 2019,Ladies Denim Designer - Manchester Your new c...,Manchester,£25000.00 - £35000.00 per annum,denim designer
3885,https://www.drapersjobs.com/job/2801225/assist...,Danielle Ward Recruitment Ltd,15 Feb 2019,This well-established and successful business ...,North West England,c£20-£26,assistant merchandiser footwear accessories
3886,https://www.drapersjobs.com/job/2801233/men-s-...,Danielle Ward Recruitment Ltd,15 Feb 2019,A great opportunity has arisen for a Men’s Jac...,North West England,c£20-£30,men s designer jackets and sweats
3887,https://www.accountancyage.com/jobs/job/901488...,AJ Chambers,13 Feb 2019,AJ Chambers are currently working alongside a ...,"Ipswich, Suffolk",£31,senior accountant top firm
3888,https://www.accountancyage.com/jobs/job/901486...,Robert Half,13 Feb 2019,RobertHalf Oxfordshire are delighted to be par...,"England, Oxfordshire, Oxford",£40000 - £45000 per annum,finance analyst
3889,https://www.drapersjobs.com/job/2801184/intern...,Elite Associates,14 Feb 2019,"My client, an emerging international based clo...",East London,£28000 - £32000 per annum,international wholesale executive
3890,https://www.drapersjobs.com/job/2801220/pr-exe...,Four Seasons Recruitment,15 Feb 2019,"My client, a beautiful British heritage brand,...",City of London,£22000 - £25000 per annum,pr executive luxury british heritage brand
3891,https://www.drapersjobs.com/job/2801212/assist...,Hays,15 Feb 2019,Assistant Garment Technologist - leading Brand...,Manchester,£16000.00 - £18000.00 per annum,assistant garment technologist
3892,https://www.drapersjobs.com/job/2801192/fashio...,People Marketing,14 Feb 2019,This forward thinking fashion business have an...,"Leicester, Leicestershire",£Dependent Upon Experience,fashion graphic designer
3893,https://www.drapersjobs.com/job/2801190/brand-...,TRP Recruitment,14 Feb 2019,International Brand Manager - Womenswear Young...,London,£45000 - £50000 per annum,brand manager young trend fashion womenswear
3894,https://www.drapersjobs.com/job/2801228/studio...,Elite Associates,15 Feb 2019,We are looking for a Studio Assistant to join ...,London,dependent on experience,studio assistant fashion
3895,https://www.drapersjobs.com/job/2801221/crm-an...,Four Seasons Recruitment,15 Feb 2019,Amazing entry level role with a salary of up t...,London,Up to £26000 per annum,crm and social media exec luxury homeware
3896,https://www.drapersjobs.com/job/2801195/ladies...,Danielle Ward Recruitment Ltd,14 Feb 2019,This successful supplier to the High Street re...,South East England,c£20-£26,ladies lingerie activewear designer
3897,https://www.drapersjobs.com/job/2801218/creati...,Repeat Clothing London,15 Feb 2019,Established and successful company requires a ...,London (Greater),£30K upwards depending on experience,creative cad pattern cutter product developer
3898,https://www.drapersjobs.com/job/2801194/senior...,Glamorous,14 Feb 2019,True Decadence is epitomised by ultra-flatteri...,"Manchester, Greater Manchester",£Competitive,senior designer
3899,https://www.accountancyage.com/jobs/job/901505...,Robert Half,13 Feb 2019,Robert Half Finance and Accounting are seeking...,"Wales, Cardiff",£38000 - £45000 per annum,practice accountant partner designate
3900,https://www.drapersjobs.com/job/2801243/crm-ex...,People Marketing,15 Feb 2019,A quintessential British Menswear brand is loo...,London (Greater),£Dependent Upon Experience,crm executive
3901,https://www.drapersjobs.com/job/2801249/womens...,People Marketing,15 Feb 2019,Womenswear Sales and Account Manager – The C...,"London (East), London (Greater)",£Competitive + DOE,womenswear sales and account manager
3902,https://www.accountancyage.com/jobs/job/901499...,Robert Half,13 Feb 2019,We are looking for a junior purchase ledger fo...,"England, Hertfordshire, St. Albans",£9 - £11 per hour,purchase ledger
3903,https://www.drapersjobs.com/job/2801198/design...,Danielle Ward Recruitment Ltd,14 Feb 2019,We are working closely with this well-establis...,North West England,c£25,designer wallcoverings and home d cor
...,...,...,...,...,...,...,...
3944,https://jobs.telegraph.co.uk/job/11430460/sale...,BMS Performance,13 Feb 2019,This job is a fantastic opportunity to join on...,Chiswick,£80000 - £90000 per annum + Company Package,sales director southern europe
3945,https://jobs.telegraph.co.uk/job/11430558/oper...,Nevard Roland,15 Feb 2019,Operations Director Ref:17198 South Wales Eng...,South Wales,Up to £70000 per annum + + Bonus,operations director
3946,https://jobs.telegraph.co.uk/job/11430465/dire...,Barnaby Stewart Executive Search,13 Feb 2019,Our client is a Globally recognised onsite eng...,London,Base : £85k Benefits: Generous Senior Executiv...,director of finance fd x
3947,https://jobs.telegraph.co.uk/job/11430470/oper...,Novo Executive Search and Selection,13 Feb 2019,THE CLIENT Our client is an international man...,West Midlands Region,Competitive,operations manager
3948,https://pmjobs.cipd.co.uk/job/177586/payroll-m...,CONSULT HR,14 Feb 2019,Payroll Manager Bournemouth Ref: DBEC7087 If...,"Bournemouth, England",Negotiable,payroll manager
3949,https://pmjobs.cipd.co.uk/job/177606/hr-and-pa...,Hays,14 Feb 2019,"HR & Payroll Assistant - Insurance - £28,000-£...","London, England",Negotiable,hr payroll assistant
3950,https://jobs.telegraph.co.uk/job/11430502/busi...,Listgrove Ltd,14 Feb 2019,Business Development Manager Based in Cambrid...,Cambridgeshire,Commensurate with experience,business development manager
3951,https://jobs.telegraph.co.uk/job/11430511/seni...,Barnaby Stewart Executive Search,14 Feb 2019,Our client is a leading International Mechanic...,"London (Central), London (Greater)",£95k base,senior project manager spm
3952,https://jobs.telegraph.co.uk/job/11430483/divi...,Barnaby Stewart Executive Search,14 Feb 2019,Our client is a major civil and building contr...,Home Counties,£150k base,divisional finance director dfd ft
3953,https://pmjobs.cipd.co.uk/job/177633/hr-adviso...,Hays,15 Feb 2019,"Permanent HR Advisor role c£30,000 Our clien...","Fakenham, England",£28000.00 - £32000.00 per annum,hr advisor
3954,https://jobs.telegraph.co.uk/job/11430464/seni...,BMS Performance,13 Feb 2019,North west cloud services vendor Disrupting th...,Manchester,£40000.00 - £55000.00 per annum + OTE 120k + B...,senior business development manager
3955,https://pmjobs.cipd.co.uk/job/177569/hr-and-od...,Sixtown Housing,14 Feb 2019,We are a growing business looking for an exper...,"Bury, Greater Manchester",Up to £50,hr and od business manager
3956,https://jobs.telegraph.co.uk/job/11430510/pack...,Henderson Brown,14 Feb 2019,Role: Packaging Manager Location: Hertfordshi...,Hertfordshire,£35000.00 - £40000 per annum,packaging manager
3957,https://jobs.telegraph.co.uk/job/11430457/head...,BMS Performance,13 Feb 2019,With zero real wage growth forecasted for 2018...,London,£50000 - £80000 per annum + Company Package,head of sales
3958,https://pmjobs.cipd.co.uk/job/177609/hr-and-pa...,Hays,14 Feb 2019,HR an Payroll Manager Your new company ...,"Millom, England",£40000.00 - £45000.00 per annum,hr and payroll manager
3959,https://jobs.telegraph.co.uk/job/11430545/head...,Barnaby Stewart Executive Search,15 Feb 2019,Our client is an internationally recognised co...,"London (Central), London (Greater)",Base : £110k Benefits:Full executive package B...,head of design international hodi
3960,https://pmjobs.cipd.co.uk/job/177583/regional-...,Hays,14 Feb 2019,An exciting opportunity for a Regional Event R...,"South West England, England",£28000.00 - £32000.00 per annum,regional events recruiter
3961,https://www.drapersjobs.com/job/2801163/part-t...,Elite Associates,13 Feb 2019,Part-time Skincare Sales Consultant A chance...,London,Up to £9.5 per hour,part time skincare sales consultant
3962,https://www.drapersjobs.com/job/2801142/sales-...,Fashion And Retail Personnel,13 Feb 2019,Sales & Account Manager - Menswear Based Birmi...,Birmingham,£25000 - £40000 per annum + salary is agency g...,sales account manager menswear
3963,https://jobs.telegraph.co.uk/job/11430406/regi...,BMS Performance,12 Feb 2019,Working for this market leading business will ...,Manchester,£45000.00 - £60000.00 per annum + Company Car ...,regional sales manager formwork falsework
3964,https://pmjobs.cipd.co.uk/job/177457/interim-h...,Hays,11 Feb 2019,Interim HR Process Harmonisation Lead - Immedi...,"London, England",£500.00 - £650.00 per day,interim hr process harmonisation lead
3965,https://www.accountancyage.com/jobs/job/902575...,Robert Half,01 Mar 2019,"Assistant Management Accountant £25,000 - £30,...","England, Bristol",£25000 - £30000 per annum + study,assistant management accountant
3966,https://www.jobstoday.co.uk/job/32058935/servi...,Interaction - Worthing,10 Mar 2019,Job Title: Service Engineer Location: Bas...,Wellingborough,25000.00 - 45000.00 GBP Annual,service engineer
3967,https://www.jobstoday.co.uk/job/32059140/genom...,Trilogy International,08 Mar 2019,Genomics/Project Management/PM/Clinical Scient...,Cambridge,550.00 GBP Daily,genomics project manager
3968,https://www.jobstoday.co.uk/job/32059317/gener...,Xercise4less,10 Mar 2019,"General Manager ??23, - ??3, per annum (OTE ...",North Lanarkshire,Competitive,general manager glasgow
3969,https://www.jobstoday.co.uk/job/32059936/progr...,Trilogy International,08 Mar 2019,Genomics/Project Management/PM/Clinical Scient...,Cambridge,900.00 GBP Daily,programme manager genomics
3970,https://www.jobstoday.co.uk/job/32061562/paid-...,Recruitment Revolution.com Ltd,08 Mar 2019,Paid Media Team Lead / Senior PPC Brighton...,Brighton,Competitive + Excellent Benefits & Perks,paid media team lead senior ppc
3971,https://www.jobstoday.co.uk/job/32061640/senio...,Blue Arrow High Street - Glasgow,08 Mar 2019,We have a fantastic opportunity for you if you...,North Lanarkshire,22000.00 - 30000.00 GBP Annual,senior permanents consultant
3972,https://www.jobstoday.co.uk/job/32062588/junio...,Advanced,08 Mar 2019,Job Description Advanced are one of the UK's...,Leeds,Competitive,junior support consultant
3973,https://www.jobstoday.co.uk/job/32062867/home-...,Constance Care,10 Mar 2019,Home Carer - ??8.75 per hour - Guaranteed Hour...,North Lanarkshire,,home carer east kilbride ph

In [14]:
df_24['salary'] = df_24['salary'].replace('£','-')
df_24['company'] = df_24['company'].replace('','-')

In [15]:
df_reed['date_listed'] = df_reed['date_listed'].replace('Today', '13-03-2019')

In [16]:
import datetime
df_today['date_listed'] = df_today['date_listed'].apply(lambda x: datetime.datetime.strptime(x, "%d %b %Y").strftime("%d-%m-%Y"))

In [17]:
df_techno['date_listed'] = df_techno['date_listed'].replace(regex= r'^today*', value='13th march').str.split(',').str[0]
df_techno['date_listed'] = df_techno['date_listed'].replace('yesterday','12th march')
df_techno['date_listed'] = df_techno['date_listed'].str.replace('th','').str.replace('rd','').str.replace('nd','').str.replace('st','')
df_techno['date_listed'] = df_techno['date_listed'].apply(lambda x: datetime.datetime.strptime(x, "%d %B").strftime("%d-%m-2019"))
# df_techno['date_listed'].value_counts()

In [19]:
df_indeed['date_listed'] = '21-03-2019'

In [20]:
all_dfs = [df_reed,df_24,df_today, df_indeed ,df_techno]

In [21]:
df = pd.concat(all_dfs).reset_index(drop=True)

In [22]:
df['location'] = df['location'].str.lower()

In [23]:
lat_long = pd.read_csv("Uk_cities_long_lat.csv")

df = df.merge(lat_long,how ='left', right_on = 'City',left_on = 'location')

In [24]:
len(df[df['lat'].isnull()])  #15439 with no coordinates
# df[df['lat'].isnull()]['']
df.loc[df['lat'].isnull(),['lat']] = 51.509865
df.loc[df['lat'].isnull(),['long'] ]= -0.118092

In [25]:
df.drop(columns='City',inplace= True)

In [25]:
df.to_json('all_jobs.json', orient = 'records')

In [26]:
df.head()

,URL,company,date_listed,description,location,salary,title,lat,long
0,https://www.reed.co.uk/jobs/clinical-developme...,nhs greater glasgow clyde,13-03-2019,Apply on employer's website ...,lanarkshire,£32.157 - £42.544 per annum,clinical development fellow in urology,51.509865,NaN
1,https://www.reed.co.uk/jobs/mixed-tax-senior-t...,mcginnis loy associates ltd,13-03-2019,Apply now ...,london,£35.000 - £45.000 per annum,mixed tax senior tax accountant top accounting...,51.509865,-0.118092
2,https://www.reed.co.uk/jobs/marketing-executiv...,reed marketing creative,13-03-2019,Apply now ...,london,£13.50 - £18.00 per hour,marketing executive leading celebrity restaura...,51.509865,-0.118092
3,https://www.reed.co.uk/jobs/new-product-develo...,consult search selection,13-03-2019,Apply now ...,southyorkshire,£25.000 - £30.000 per annum,new product development engineer,51.509865,NaN
4,https://www.reed.co.uk/jobs/technical-accounta...,insight recruitment solutions limited,13-03-2019,Apply now ...,london,£55.000 - £60.000 per annum,technical accountant,51.509865,-0.118092

In [26]:
# df_list = df.values.tolist()

In [27]:
# with open(output_file, 'w') as f:
#     json.dump(df_list, f)